In [1]:
import numpy as np  # np è a caso, posso chiamarlo zio gigi

In [2]:
np.pi

3.141592653589793

In [10]:
# la forza della libreria numpy è che se io ho un vettore (array)...
x=np.array([1,.6,5,2,1,23,1,np.nan])  # se io metto una stringa, poi sono tutte stringhe 
print(x)
# np.nan --> missing values 

[ 1.   0.6  5.   2.   1.  23.   1.   nan]


In [11]:
x

array([ 1. ,  0.6,  5. ,  2. ,  1. , 23. ,  1. ,  nan])

In [12]:
x+1

array([ 2. ,  1.6,  6. ,  3. ,  2. , 24. ,  2. ,  nan])

In [13]:
array([nan])

NameError: name 'array' is not defined

In [14]:
x2=[1,.6,5,2,1,np.nan,23,1,np.inf]

In [15]:
y2=[]
for wl in x2:
    y2.append(el+1)
print(y2)

NameError: name 'el' is not defined

In [17]:
y2=list(np.array(x2)+1)
print(y2)

[2.0, 1.6, 6.0, 3.0, 2.0, nan, 24.0, 2.0, inf]


In [20]:
x=[2,1.6,6,3,2,np.nan,24,2,np.inf]
v=[]
for el in x:
    if el > 5:
        v.append(el)
print(v)

[6, 24, inf]


In [21]:
[el for el in x if el>5] # stessa cosa 

[6, 24, inf]

In [26]:
x=np.array([2,1.6,6,3,2,24,2,np.inf])
print(x>5)
print(x[x>5])

[False False  True False False  True False  True]
[ 6. 24. inf]


In [27]:
print((x>5)&(x<12))
print(x[(x>5)&(x<12)])

[False False  True False False False False False]
[6.]


In [28]:
print((x>5)|(x<12))
print(x[(x>5)|(x<12)])

[ True  True  True  True  True  True  True  True]
[ 2.   1.6  6.   3.   2.  24.   2.   inf]
