In [2]:
import numpy as np

In [34]:
# array 
v=np.array([1,4,3,1,5],dtype="float")
print(v)
print(type(v))

[1. 4. 3. 1. 5.]
<class 'numpy.ndarray'>


In [5]:
v.sort()

In [6]:
v.max()

5

In [7]:
v.sum()

14

In [8]:
v.dot() # errore perchè manca un argomento

TypeError: Required argument 'b' (pos 1) not found

In [10]:
v.dot(w)

NameError: name 'w' is not defined

In [11]:
np.dot(v,w)

NameError: name 'w' is not defined

In [12]:
np.sin(v)

array([ 0.84147098,  0.84147098,  0.14112001, -0.7568025 , -0.95892427])

In [13]:
v+1  # con numpy si possono fare operazioni su un vettore. Prima non potevo farlo. 

array([2, 2, 4, 5, 6])

In [14]:
v*2

array([ 2,  2,  6,  8, 10])

In [15]:
v**2

array([ 1,  1,  9, 16, 25])

In [17]:
A=np.array([[1,2,0],[np.pi,0,np.sqrt(5)],[0,0,1]])

In [19]:
x=np.ones(3)
print(A)
print(x)

[[1.         2.         0.        ]
 [3.14159265 0.         2.23606798]
 [0.         0.         1.        ]]
[1. 1. 1.]


In [20]:
np.dot(A,x)

array([3.        , 5.37766063, 1.        ])

In [21]:
# per vedere shape
x.shape

(3,)

In [22]:
A.shape  # La shape di una array è una tupla che sono immutabili

(3, 3)

In [24]:
x=np.ones((3,1))
print(x)

[[1.]
 [1.]
 [1.]]


In [25]:
x.shape

(3, 1)

In [26]:
b=np.dot(A,x)
b.shape

(3, 1)

In [27]:
y=np.ones((1,3))
print(y)

[[1. 1. 1.]]


In [28]:
np.dot(A,y)

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [29]:
A

array([[1.        , 2.        , 0.        ],
       [3.14159265, 0.        , 2.23606798],
       [0.        , 0.        , 1.        ]])

In [30]:
A.T   # trasposta

array([[1.        , 3.14159265, 0.        ],
       [2.        , 0.        , 0.        ],
       [0.        , 2.23606798, 1.        ]])

In [31]:
np.linalg.det(A)  # determinante matrice di A

-6.283185307179585

In [33]:
np.dot(np.linalg.inv(A),b)

array([[1.],
       [1.],
       [1.]])

In [37]:
x=np.arange(0,100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [38]:
print(x.shape)

(100,)


In [40]:
x.reshape((5,5,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [ ]:
### FINISCI